core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('agendamentos', include('agendamentos.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('sintomas/', views.sintomas_view, name='sintomas'),

    path('atendimento/', views.atend_view, name='atendimento'),

    path('cadastro-pet/', views.cadastro_pet_view, name='cadastro_pet'),
    
    path('cadastro-funcionario/', views.cadastro_funcio_view, name='cadastro_funcionario'),
    path('sobrenos/', views.sobrenos_view, name='sobrenos'),
    path('comentaios/', views.comentarios_view, name='comentarios'),
]

home/models.py
from django.db import models
 
class Funcionario(models.Model):
    nome = models.CharField(max_length=30)
    cpf = models.CharField(max_length=15)
    endereco = models.CharField(max_length=30)
    sexo = models.CharField(max_length=1)
    tel = models.CharField(max_length=15)
    nasc = models.DateField(blank=True, null=True)
    
    
    def __str__(self):
        return self.nome
 
class Veterinario(models.Model):
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE,
                                    related_name='Veterinario')
    doutor = models.CharField(max_length=40)
    crmv = models.CharField(max_length=30)  #Exemplo: CRMV-SP 12345
   
    def __str__(self):
        return self.doutor

    
class Tutor(models.Model):
    tutor_nome = models.CharField(max_length=30)
    cpf = models.CharField(max_length=15)
    tel = models.CharField(max_length=15)
    ender = models.CharField(max_length=15)
   
    def __str__(self):
        return self.tutor_nome

class Animal(models.Model):
    Animal_choices = [
        ('gato', 'Gato'),
        ('cachorro', 'Cachorro'),
        ('aves', 'Aves'),
    ]
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE,
                                 related_name='Animal')
    nome_pet = models.CharField(max_length=30, null=True, blank=True)
    peso_pet = models.FloatField(max_length=30)
    idade_pet = models.CharField(max_length=2, null=True, blank=True)
    raca_pet = models.CharField(max_length=30, null=True, blank=True)
    tipo = models.CharField(max_length=30, choices=Animal_choices, default='gato')
    
    def __str__(self):
        return f'{self.nome_pet} ({self.get_tipo_display()})'
        

class Sintomas(models.Model):
    Sintomas_choices = [
        ('verde', 'Verde'),
        ('amarelo', 'Amarelo'),
        ('vermelho', 'Vermelho'),
    ]
    sintomas = models.CharField(max_length=14, null=True, blank=True)
    grau_sint = models.CharField(max_length=30, choices=Sintomas_choices, default='verde')
    descricao = models.CharField(max_length=30)
    
    def __str__(self):
        return self.sintomas
    
class Consulta(models.Model):
    Sintomas_choices = [
        ('verde', 'Verde'),
        ('amarelo', 'Amarelo'),
        ('vermelho', 'Vermelho'),
    ]
    sintomas = models.ForeignKey(Sintomas, on_delete=models.CASCADE,
                                 null=True, related_name='Consulta')
    nome_proced = models.CharField(max_length=30, default=True)
    duracao = models.DateTimeField(max_length=30, null=True, blank=True)
    
    grau_de_risco = models.CharField(max_length=30, null=True, blank=True,choices=Sintomas_choices, default='verde')
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    veterinario = models.ForeignKey(Veterinario, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nome_proced

class Loja(models.Model):
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE,
                                    related_name='Loja')
    veterinario = models.ForeignKey(Veterinario, on_delete=models.CASCADE,
                                    related_name='Loja')              
    nome_loja = models.CharField(max_length=100)  
    endereco = models.CharField(max_length=200)  
    telefone = models.CharField(max_length=20)  
    email = models.EmailField()  

    def __str__(self):
        return self.nome_loja
    
class Agendamento(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE) 
    nome_agend = models.CharField(max_length=30, null=True, blank=True)
    consulta = models.ForeignKey(Consulta, on_delete=models.CASCADE)          
    veterinario = models.ForeignKey(Veterinario, on_delete=models.CASCADE)                                                  
    data_agend = models.DateTimeField(null=True, blank=True)
     
    def __str__(self):
        return self.nome_agend

home/forms.py
# from django import forms
# from .models import Animal

# class PetForm(forms.ModelForm):
#     class Meta:
#         model = Animal
#         fields = ['paciente', 'nome_pet', 'peso_pet', 'idade_pet', 'raca_pet', 'tipo']

home/views.py
from urllib import request
from django.shortcuts import redirect, render
from django.shortcuts import render, redirect
from .models import Animal, Consulta, Tutor, Veterinario
from home.models import Animal, Funcionario, Tutor

def login_view(request):
    return render(request, 'login.html')

def sintomas_view(request):
    return render(request, 'sintomas.html')

def atend_view(request):
        
    if request.method == 'POST':
        animal_id = request.POST['animal']
        veterinario_id = request.POST['veterinario']
        grau_de_risco = request.POST['grau_de_risco']
        nome_proced = request.POST['nome_proced']
        agendamento = request.POST['agendamento']
        
        try:
            animal = Animal.objects.get(id=animal_id)
        except Animal.DoesNotExist:
            return redirect('status_agendamentos')  # redirecionar para a página de erro
        
        try:
            veterinario = Veterinario.objects.get(id=veterinario_id)
        except Veterinario.DoesNotExist:
            return redirect('status_agendamentos')  # redirecionar para a página de erro

        consulta = Consulta(
            duracao=agendamento,
            nome_proced=nome_proced,
            grau_de_risco=grau_de_risco,
            veterinario=veterinario,
            animal=animal
        )
        consulta.save()
        return redirect('sintomas')
    
    # Obter todos os animais e veterinários para o contexto
    animais = Animal.objects.all()
    veterinarios = Veterinario.objects.all()
    context = {
        "animais": animais,
        "veterinarios": veterinarios
    }
    return render(request, 'atend.html', context)
            
            
            
            # Você pode querer lidar com a exceção de forma adequada, talvez com uma mensagem de erro
            # return render(request, 'atend.html', {'veterinarios': Veterinario.objects.all(), 'error': 'Tutor não encontrado.'})




def cadastro_pet_view(request):
    if request.method == 'POST':
        tutor_id = request.POST['tutor']  # Obtendo o ID do tutor
        nome_pet = request.POST['nome_pet']
        peso_pet = request.POST['peso_pet']
        idade_pet = request.POST['idade_pet']
        raca_pet = request.POST['raca_pet']
        tipo = request.POST['tipo']
        
        # Buscar o objeto Tutor correspondente ao ID
        try:
            tutor = Tutor.objects.get(id=tutor_id)
        except Tutor.DoesNotExist:
            # Você pode querer lidar com a exceção de forma adequada, talvez com uma mensagem de erro
            return render(request, 'CadastroPet.html', {'tutores': Tutor.objects.all(), 'error': 'Tutor não encontrado.'})
        
        # Criar o objeto Animal
        animal = Animal(
            tutor=tutor,  # Passando o objeto Tutor
            nome_pet=nome_pet,
            peso_pet=peso_pet,
            idade_pet=idade_pet,
            raca_pet=raca_pet,
            tipo=tipo
        )
        animal.save()
        return redirect('home')
    
    tutores = Tutor.objects.all()
    context = {
        'tutores': tutores
    }
    
    return render(request, 'CadastroPet.html', context)


def cadastro_funcio_view(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        cpf = request.POST.get('cpf')
        endereco = request.POST.get('endereco')
        sexo = request.POST.get('sexo')
        tel = request.POST.get('tel')
        nasc = request.POST.get('nasc')

        # Verifica se todos os campos estão preenchidos
        if nome and cpf and endereco and sexo and tel and nasc:
            # Cria e salva o objeto Funcionario
            funcionario = Funcionario(nome=nome, cpf=cpf, endereco=endereco, sexo=sexo, tel=tel, nasc=nasc)
            print(funcionario)
            funcionario.save()
            return redirect('home')  # Redireciona para a página inicial ou outra de sua escolha
        else:
            # Retorna uma mensagem de erro se houver campos em branco
            return render(request, 'CadFuncio.html', {'error': 'Por favor, preencha todos os campos obrigatórios.'})

    return render(request, 'CadFuncio.html')

    
def home_view(request):
    return render(request, 'home.html')

def sobrenos_view(request):
    return render(request, 'sobrenos.html')

def comentarios_view(request):
    return render(request, 'comentarios.html')

home/templates/CadFuncio.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cadastro Funcionario</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/CadFunc.css' %}">    
  </head>
  <body>
    <div class="signup-container">
      <img style="max-width: 300px;" src="{% static 'img/Logo.png' %}" alt="Logo">
      <h2>Cadastro Funcionário</h2>
      <form action="" method="POST">
        {% csrf_token %}
        <fieldset class="module aligned">
          <div class="form-row field-nome">
            <label for="id_nome">Nome:</label>
            <input
              type="text"
              name="nome"
              class="vTextField"
              maxlength="30"
              id="id_nome"
              required
            />
          </div>
          <div class="form-row field-cpf">
            <label class="required" for="id_cpf">CPF:</label>
            <input
              type="text"
              name="cpf"
              class="vTextField"
              maxlength="15"
              id="id_cpf"
              required
            />
          </div>
          <div class="form-row field-endereco">
            <label for="id_endereco">Endereço:</label>
            <input
              type="text"
              name="endereco"
              class="vTextField"
              maxlength="30"
              id="id_endereco"
              required
            />
          </div>
          <div class="form-row field-sexo">
            <label for="id_sexo">Sexo:</label>
            <input
              type="text"
              name="sexo"
              class="vTextField"
              maxlength="1"
              id="id_sexo"
              required
            />
          </div>
          <div class="form-row field-telefone">
            <label class="required" for="id_tel">Telefone:</label>
            <input
              type="text"
              name="tel"
              class="vTextField"
              maxlength="15"
              id="id_tel"
              required
            />
          </div>
          <div class="form-row field-nasc">
            <label for="id_nasc">Data de Nascimento:</label>
            <input
              type="date"
              name="nasc"
              id="id_nasc"
              required
            />
          </div>
        </fieldset>
        <div class="submit-row">
          <button type="submit" class="save-button">Salvar</button>
        </div>
      </form>
    </div>
  </body>
</html>

home/templates/CadastroPet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Cadastro de Pet</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/CadPet.css' %}">
</head>
<body>
    <div class="signup-container">
        <img style='max-width: 300px;' src="{% static 'img/Logo.png' %}" alt="Logo">
        <h2>Cadastrar Novo Pet</h2>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <form method="post">
            {% csrf_token %}
            <fieldset class="module aligned">
                <div class="form-row field-tutor">
                    <div>
                        <div class="flex-container">
                            <label for="tutor">Tutor:</label>
                            <select name="tutor" id="tutor" required>
                                <option value="">Selecione um Tutor</option>
                                {% for tutor in tutores %}
                                    <option value="{{ tutor.id }}">{{ tutor.tutor_nome }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>

                <div class="form-row field-nome_pet">
                    <div>
                        <div class="flex-container">
                            <label for="nome_pet">Nome do Pet:</label>
                            <input type="text" name="nome_pet" required>
                        </div>
                    </div>
                </div>

                <div class="form-row field-peso_pet">
                    <div>
                        <div class="flex-container">
                            <label class="required" for="peso_pet">Peso do Pet:</label>
                            <input type="number" name="peso_pet" step="any" required id="peso_pet">
                        </div>
                    </div>
                </div>

                <div class="form-row field-idade_pet">
                    <div>
                        <div class="flex-container">
                            <label for="idade_pet">Idade do Pet:</label>
                            <input type="text" name="idade_pet" class="vTextField" maxlength="2" id="idade_pet">
                        </div>
                    </div>
                </div>

                <div class="form-row field-raca_pet">
                    <div>
                        <div class="flex-container">
                            <label for="raca_pet">Raça do Pet:</label>
                            <input type="text" name="raca_pet" class="vTextField" maxlength="30" id="raca_pet">
                        </div>
                    </div>
                </div>

                <div class="form-row field-tipo">
                    <div>
                        <div class="flex-container">
                            <label class="required" for="tipo">Tipo:</label>
                            <select name="tipo" id="tipo" required>
                                <option value="gato" selected>Gato</option>
                                <option value="cachorro">Cachorro</option>
                                <option value="aves">Aves</option>
                            </select>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="submit-row">
                <button type='submit'>Cadastrar</button>
            </div>
        </form>
    </div>
</body>
</html>

home/templates/atend.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Plan.Vet - Atendimento</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/atend.css' %}">  
  </head>
  <body>
    <!-- Header and Navigation -->
    <header>
      <div class="header-container">
        <div class="logo-container">
          <img style='max-width: 60px;' src="{% static 'img/Logo.png' %}" alt="Logo">
        </div>
        <nav class="nav-links">
          <a href="{% url 'home' %}">Home</a>
          <li><a href="{% url 'cadastro_pet' %}">cadpet</a></li>
        </nav>
        <div class="profile">
          <a href="{% url 'login' %}">
              <img src="{% static 'img/perfil.png' %}" alt="Logo">
          </a>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <main class="signup-container">
      <h2>Procedimento</h2>
      <form action="{% url 'atendimento' %}" method="POST">
        {% csrf_token %}
        <fieldset class="module aligned">
          <div class="form-row field-animal">
            <label for="id_animal">Animal:</label>
            <select name="animal" id="id_animal" required>
              <option value="">Selecione o animal</option>
              {% for animal in animais %}
                <option value="{{ animal.id }}">{{ animal.nome_pet }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-row field-veterinario">
            <label for="id_veterinario">Veterinário:</label>
            <select name="veterinario" id="id_veterinario" required>
              <option value="">Selecione o veterinário</option>
              {% for veterinario in veterinarios %}
                <option value="{{ veterinario.id }}">{{ veterinario.doutor }}</option>
              {% endfor %}
            </select>
          </div>
          
          <!-- Grau de Risco -->
          <div class="form-row field-grau-risco">
            <label for="id_grau_risco">Grau de Risco:</label>
            <select name="grau_de_risco" id="id_grau_risco" required>
              <option value="">Selecione o grau de risco</option>
              <option value="verde">Verde</option>
              <option value="amarelo">Amarelo</option>
              <option value="vermelho">Vermelho</option>
            </select>
          </div>
          
          <div class="form-row field-atend">
            <label for="id_nome_proced">Procedimento:</label>
            <input type="text" name="nome_proced" class="vTextField" maxlength="30" id="id_nome_proced" placeholder="Informe o procedimento" required />
          </div>
          <div class="form-row field-agend">
            <label class="required" for="id_agend">Agendamento:</label>
            <input type="datetime-local" name="agendamento" id="id_agend" required />
          </div>
        </fieldset>
      
        <div class="submit-row">
          <button type="submit" class="btn-submit">Salvar</button>
          <a href="{% url 'atendimento' %}" class="btn-submit">Adicionar Outro</a>
        </div>
      </form>
      
    </main>

    <!-- Footer -->
    <footer>
      <p>&copy; 2024 Plan.Vet. Todos os direitos reservados.</p>
    </footer>
  </body>
</html>

home/templates/comentarios.html
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Fale Conosco</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/comentarios.css' %}">
        
    </head>
    <body>

    <!-- Navegação -->
    <nav class="navbar">
        <div class="container">
            <h1>Plan.Vet</h1>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <!-- Adicione outros links conforme necessário -->
            </ul>
        </div>
    </nav>

    <!-- Seção principal -->
    <main class="main-content">
        <div class="container">
            <h2>Fale Conosco</h2>
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="nome">Nome:</label>
                    <input type="text" id="nome" name="nome" required>
                </div>
                <div class="form-group">
                    <label for="email">E-mail:</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="comentario">Comentário:</label>
                    <textarea id="comentario" name="comentario" placeholder="Digite seu comentário aqui..." required></textarea>
                </div>
                <button type="submit" {% static 'home' %}>Enviar Comentário</button>
            </form>
        </div>
    </main>

    <!-- Rodapé -->
    <footer class="footer">
        <div class="container">
            <p>&copy; 2024 Plan.Vet. Todos os direitos reservados.</p>
        </div>
    </footer>

    </body>
    </html>

home/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block 'title' %}Home{% endblock 'title' %}


  {% block 'content' %}
  {% include 'partials/navbar.html' %}

    <main>
      <div class="background-image" style="background-image:url({% static 'img/fundo.png' %})" >
        <div class="info-container">
          <h2>Informações das Lojas</h2>
          <p>
            Localização, horários de funcionamento e outras informações
            relevantes.
          </p>
          <!-- Adicione mais detalhes aqui conforme necessário -->
        </div>
      </div>
    </main>

    
  {% include 'partials/footer.html' %}
  {% endblock 'content' %}
  
</html>

home/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
   
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
  </head>
  <body>
    <div class="login-container">
        <img style='max-width: 300px;'src="{% static 'img/Logo.png' %}" alt="Logo">
      <form action="#" method="POST">
        {% csrf_token %}
          <div class="input-group">
              <label for="username">Usuário</label>
              <input type="text" id="username" name="username" required>
          </div>
          <div class="input-group">
              <label for="password">Senha</label>
              <input type="password" id="password" name="password" required>
          </div>
          <div class="submit-row">
            <a href="{% url 'home' %}" class="btn-submit" onclick="alert('login efetuado!')">Entrar</a>
      </form>
      <div class="options" >
          <a href="#">Recuperar Senha</a>
          <a href="#">Criar Conta Nova</a>
      </div>
  </div>
    </div>
  </body>
</html>

home/templates/sintomas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sintomas</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/sintomas.css' %}">

    

</head>
<body>
    <div class="container">
        <img style='max-width: 300px;'src="{% static 'img/Logo.png' %}" alt="Logo">
        <form action="#" method="POST">
            <div class="input-group">
                <label for="sintoma">Nome</label>
                <input type="text" id="sintoma" name="sintoma" required>
            </div>
            <div class="input-group">
                <label for="grau_risco">Grau de Risco</label>
                <input type="text" id="grau_risco" name="grau_risco" required>
            </div>
            <div class="input-group">
                <label for="descricao">Descrição</label>
                <input type="text" id="descricao" name="descricao">
            </div>
            <div class="submit-row">
                <a href="{% url 'status_agendamentos' %}" class="btn-submit">Salvar</a>
                <input
                  type="submit"
                  value="Salvar e adicionar outro(a)"
                  class="btn-submit"
                  name="_addanother"
                />
            <!-- <button type="submit" class="btn">Salvar</button> -->
        </form>
    </div>
</body>
</html>

home/templates/sobrenos.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sobre Nós - Plan.Vet</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/sobrenos.css' %}">
</head>
<body>
    <!-- Navbar -->
    <header>
        <nav class="navbar">
            <div class="logo">
                <img src="{% static 'img/Logo.png' %}" alt="Logo">
            </div>
            <ul class="nav-links">
                <li><a href="{% url 'home' %}">Home</a></li>
            </ul>
        </nav>
    </header>

    <!-- Main -->
    <main>
        <section class="sobre-nos">
            <h1>Sobre Nós</h1>
            <p>
                A Plan.Vet é uma clínica veterinária dedicada ao cuidado e bem-estar dos pets, proporcionando 
                atendimento de qualidade e soluções completas para a saúde dos animais. Nossa equipe é composta 
                por profissionais especializados, comprometidos em oferecer um ambiente acolhedor para os animais 
                e seus tutores. Estamos aqui para atender com dedicação e responsabilidade, promovendo saúde e 
                bem-estar para todos os pets.
            </p>

            <!-- Botão de direcionamento -->
            <a href="{% url 'comentarios' %}" class="btn-direcionar">Comente aqui</a>
        </section>
    </main>

    <!-- Footer -->
    <footer>
        <div class="footer-content">
            <p>&copy; 2024 Plan.Vet - Todos os direitos reservados.</p>
            <p><a href="#">Política de Privacidade</a> | <a href="#">Contato</a></p>
        </div>
    </footer>
</body>
</html> 